language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -r test/test-requirements.txt"
  - "pip install pytest-cov coveralls"
  - "pip install -e ."

# command to run tests
script:
  - pytest --cov=segpy test
  - coveralls
